# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BlitzML_new_sparse_dataset <- function(x, y) {
    .Call(`_blitzml_BlitzML_new_sparse_dataset`, x, y)
}

BlitzML_new_dense_dataset <- function(x, y) {
    .Call(`_blitzml_BlitzML_new_dense_dataset`, x, y)
}

BlitzML_new_solver <- function() {
    .Call(`_blitzml_BlitzML_new_solver`)
}

BlitzML_new_logreg_solver <- function() {
    .Call(`_blitzml_BlitzML_new_logreg_solver`)
}

BlitzML_new_linear_solver <- function() {
    .Call(`_blitzml_BlitzML_new_linear_solver`)
}

BlitzML_new_parameters <- function(params) {
    .Call(`_blitzml_BlitzML_new_parameters`, params)
}

BlitzML_solver_compute_max_l1_penalty <- function(xptr_solver, xptr_dataset, xptr_params) {
    .Call(`_blitzml_BlitzML_solver_compute_max_l1_penalty`, xptr_solver, xptr_dataset, xptr_params)
}

BlitzML_solve_problem <- function(xptr_solver, xptr_dataset, xptr_params, result, status_buffer, log_dir) {
    invisible(.Call(`_blitzml_BlitzML_solve_problem`, xptr_solver, xptr_dataset, xptr_params, result, status_buffer, log_dir))
}

BlitzML_set_tolerance <- function(xptr_solver, value) {
    invisible(.Call(`_blitzml_BlitzML_set_tolerance`, xptr_solver, value))
}

BlitzML_set_max_time <- function(xptr_solver, value) {
    invisible(.Call(`_blitzml_BlitzML_set_max_time`, xptr_solver, value))
}

BlitzML_set_max_iterations <- function(xptr_solver, value) {
    invisible(.Call(`_blitzml_BlitzML_set_max_iterations`, xptr_solver, value))
}

BlitzML_set_use_working_sets <- function(xptr_solver, value) {
    invisible(.Call(`_blitzml_BlitzML_set_use_working_sets`, xptr_solver, value))
}

