# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

create_solver_sparse_dataset <- function(x, y) {
    .Call(`_blitzml_create_solver_sparse_dataset`, x, y)
}

BlitzML_new_solver <- function() {
    .Call(`_blitzml_BlitzML_new_solver`)
}

BlitzML_new_parameters <- function(params) {
    .Call(`_blitzml_BlitzML_new_parameters`, params)
}

BlitzML_sparse_linear_solver_compute_max_l1_penalty <- function(xptr_solver, xptr_dataset, xptr_params) {
    .Call(`_blitzml_BlitzML_sparse_linear_solver_compute_max_l1_penalty`, xptr_solver, xptr_dataset, xptr_params)
}

